# Generated by Django 4.2.5 on 2023-09-26 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobCode', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='locationmodel',
            table='jobCode_locationmodel',
        ),
    ]
