# Generated by Django 4.2.5 on 2023-09-26 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobCode', '0002_alter_locationmodel_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='locationmodel',
            table='locationmodel',
        ),
    ]
